version: "3"
services:
  taxi_server:
    build:
      context: ./server
      dockerfile: Dockerfile
    container_name: taxi_szerver
    ports:
      - "8080:3000"
    volumes:
      - "./server/src:/server/src"
    environment:
      - "DB_CONNECTION=mongodb://admin:password@taxi_database:27017"
    networks:
      - taxi_net
    depends_on:
      - taxi_database

  taxi_database:
    build:
      context: ./db
      dockerfile: Dockerfile
    container_name: taxi_database
    volumes:
      - "./db/backup:/data/db"
    environment:
      # A környzeti változókat listaként (lásd 13.sor) és
      # kulcs-érték párokként is fel lehet sorolni (lásd alább)
      MONGO_INITDB_ROOT_USERNAME: "admin"
      MONGO_INITDB_ROOT_PASSWORD: "password"
    networks:
      - taxi_net
    
  db_client:
    image: mongo-express
    container_name: mongo-express
    restart: always
    ports:
      - "8081:8081"
    environment:
      - "ME_CONFIG_MONGODB_URL=mongodb://admin:password@taxi_database:27017"
    depends_on:
      - taxi_database
    networks:
      - taxi_net

networks:
  taxi_net:
    driver: bridge
